language: scala

scala:
  - 2.13.1

script:
  - cd template &&  
    sbt ++$TRAVIS_SCALA_VERSION clean coverage test && 
    sbt ++$TRAVIS_SCALA_VERSION coverageReport && 
    sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

sudo: false
